# Generated by Django 5.2.2 on 2025-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("codigo_empleado", models.CharField(max_length=20, unique=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="trabajadores/"),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
    ]
