# Generated by Django 5.2.2 on 2025-06-21 23:09

from django.db import migrations


def add_mock_empresa(apps, schema_editor):
    """Add mock empresa data for taller mecánico"""
    Empresa = apps.get_model("empresa", "Empresa")
    
    # Only add if no empresa exists
    if not Empresa.objects.exists():
        Empresa.objects.create(
            nombre="Taller Mecánico Profesional",
            direccion="Av. Francisco de Orellana Km. 4.5\nGuayas, Ecuador",
            mision="Brindar servicios automotrices de excelencia con tecnología de punta, "
                   "garantizando la satisfacción total de nuestros clientes mediante "
                   "diagnósticos precisos, reparaciones de calidad y un equipo altamente "
                   "capacitado que se compromete con la seguridad y confiabilidad de "
                   "cada vehículo que ingresa a nuestras instalaciones.",
            vision="Ser el taller mecánico líder en la región, reconocido por nuestra "
                   "innovación tecnológica, excelencia en el servicio y compromiso "
                   "ambiental. Aspiramos a expandir nuestras operaciones manteniendo "
                   "los más altos estándares de calidad, convirtiendo cada reparación "
                   "en una experiencia confiable que fortalezca la relación a largo "
                   "plazo con nuestros clientes.",
            anio_fundacion=2009,
            ruc="1792345678001",
        )


def remove_mock_empresa(apps, schema_editor):
    """Remove mock empresa data"""
    Empresa = apps.get_model("empresa", "Empresa")
    Empresa.objects.filter(nombre="Taller Mecánico Profesional").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_mock_empresa, remove_mock_empresa),
    ]
