# Generated by Django 5.2.2 on 2025-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("pais", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
    ]
